# Generated by Django 5.2 on 2025-04-10 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_sample_student_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='analytics_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='color_accent',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('orange', 'Orange')], default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='data_sharing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_assignments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_grades',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('staff', 'Staff Only'), ('private', 'Private')], default='staff', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='push_announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='push_assignments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='push_grades',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='push_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System Default')], default='light', max_length=20),
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
                ('recorded_by', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='authentication.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.subject')),
            ],
        ),
    ]
