# Generated by Django 5.1.2 on 2025-03-17 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("behaviorpoints", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="behaviorpoint",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "Student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="behaviorpoint",
            name="teacher",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_points",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
